# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np


#### Create an array of 10 zeros 

In [2]:
import numpy as np

zeros_array = np.zeros(10)
print(zeros_array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
import numpy as np

zeros_array = np.zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [3]:
import numpy as np

ones_array = np.ones(10)
print(ones_array)


array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Create an array of 10 fives

In [11]:

fives_array = np.full(10, 5)
print(fives_array)


[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50

In [13]:
shivam = np.full(50,50)
print(shivam)

[50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50]


#### Create an array of all the even integers from 10 to 50

In [14]:
even_array = np.arange(10, 51, 2)
print(even_array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [17]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [18]:
random_number = np.random.rand()
print(random_number)

0.28826524711836476


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [20]:
random_numbers = np.random.randn(45)
print(random_numbers)

[-0.48240099  0.14546337  2.55085772  0.5601247  -0.57943143  0.15642139
  1.08178171 -0.50057847 -0.86751093  1.90235838  1.77921939  0.34365357
  1.0217678   0.09647295 -0.13101533 -0.77704718 -0.4614044   1.76172792
  0.57221272  1.046026   -0.74238728 -0.77738121 -0.10025704  0.36665498
  0.51454058  1.14044232  1.25297358 -0.09201197  1.16882769  0.67117022
  1.0019163  -0.70698681 -0.3234972  -1.01650069  0.27958824  0.63925511
 -0.45001351  0.96944801  1.03329268 -0.20525341 -1.68839166  0.30239523
 -0.77449185 -1.99645441 -1.93715893]


#### Create the following matrix:

In [23]:

scaled_numbers = 0.01 + (random_numbers * 0.495)

print(scaled_numbers)


[-0.22878849  0.08200437  1.27267457  0.28726172 -0.27681856  0.08742859
  0.54548195 -0.23778634 -0.41941791  0.9516674   0.8907136   0.18010852
  0.51577506  0.05775411 -0.05485259 -0.37463835 -0.21839518  0.88205532
  0.2932453   0.52778287 -0.3574817  -0.3748037  -0.03962723  0.19149421
  0.26469759  0.57451895  0.63022192 -0.03554593  0.58856971  0.34222926
  0.50594857 -0.33995847 -0.15013111 -0.49316784  0.14839618  0.32643128
 -0.21275669  0.48987676  0.52147987 -0.09160044 -0.82575387  0.15968564
 -0.37337347 -0.97824493 -0.94889367]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [25]:
linear_points = np.linspace(0,1,20)
print(linear_points)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [26]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [37]:
mat = np.range(12,26). reshape(3,4)
mat

AttributeError: module 'numpy' has no attribute 'range'

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [38]:
import numpy as np

mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mat)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
mat = stand_aviation

#### Get the standard deviation of the values in mat

In [39]:
my std()

SyntaxError: invalid syntax (1657121354.py, line 1)

#### Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

# Great Job!