# This is a first python class 

In [1]:
154+1541+1542+5+15+54

3311

In [4]:
2+3
3+2
1+1

2

In [3]:
a=2 
print(a)

2


In [5]:
a = "Shivam" 
print (a)

Shivam


In [6]:
x = "my name is shivam"
print (x)

my name is shivam


In [2]:
print ("my name is shivam")

my name is shivam


In [4]:
name= "shivam"
print(name)

shivam


In [5]:
name= "shivam"
print (name)

shivam


In [6]:
x=10
print(x)

10


In [27]:
X = 10

Y = 20

print("x is ", X)
print("y is ", Y)

x is  10
y is  20


In [28]:
print ("shivam")

shivam


In [29]:
10>5

True

In [30]:
100<200

True

In [31]:
10>20

False

In [32]:
10>=10

True

In [34]:
10==10

True

In [ ]:
x=1


In [43]:
if x >5:
    print("x is greater than 5")
else:
    print("x is not greater than 5")
    

x is greater than 5


In [44]:
print("hello")
print ("hello")
print ("hello")

hello
hello
hello


In [46]:
range(5)

range(0, 5)

In [53]:
for i in range(5):
    print("hello")

hello
hello
hello
hello
hello


In [55]:
x=5
y=x*3

print(y)

15


In [56]:
x=10
type(x)

int

In [60]:
x=5.28
type(x)

float

In [77]:
x="Shivam"
type(x)

TypeError: 'str' object is not callable

In [78]:
x = True 
type(x)

TypeError: 'str' object is not callable

In [2]:
age = 20
print(age)

20


In [4]:
number_1=7
number_2=8
print(number_1)
print(number_2)

7
8


In [5]:
import keyword 
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [6]:
x=50
y=2
z=x+y
print(z)

52


In [8]:
"""
this is a multi line comment

"""

x=5
print(x)

5


In [9]:
name="jhon"
age=30
print(name,age)

jhon 30


In [11]:
x,y,z=10,20,30
print(x,y,z)

10 20 30


In [14]:
x=5
x="Hello"
print(x,x)

Hello Hello


In [15]:
x=5
x="Hello"
type(x)

str

In [18]:
x="true"
type(x)

str

In [20]:
a=10
print(a)

10


In [21]:
type(a)

int

In [22]:
id(a)

140718764561480

In [23]:
f=18

In [25]:
f=20

In [26]:
print(f)

20


In [ ]:
L1=[1,2,3,4,5]
type(L1)

In [1]:
l1=[1,2,3,4,5]
type(l1)

list

In [ ]:
l1.append(10)

In [2]:
l1

[1, 2, 3, 4, 5]

In [4]:
l1[0]

1

In [5]:
l1[3]

4

In [ ]:
student = {"name":"shivam", "age":24, "Gender":"Male", "Course": "DS"}

In [17]:
student

NameError: name 'student' is not defined

In [ ]:
firstname = "shivam"
lastname = "jha"

In [25]:
firstname + lastname

NameError: name 'firstname' is not defined

In [26]:
a=10
b=10
a+b

20

In [ ]:
name = "shivam"

In [32]:
len(name)

NameError: name 'name' is not defined

In [34]:
a = "shivam"
print(a)

shivam


In [36]:
name = "shivam"
print ("my name is",name)

my name is shivam


In [8]:
a = int(input("enter 1st number")
b = int(input("enter 2nd number")
print(a+b)
        

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3962321018.py, line 1)

# practice 28th Jan 

## calculate the sum of numbers form 1 to 10

In [1]:
sum_of_numbers = 0
for num in range(1,10):
    sum_of_numbers = sum_of_numbers+num
print(sum_of_numbers)

45


In [11]:
s = 0
for i in range(1,11):
    s = s + i
    print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
s = 0
for i in range(1,11):
    s = s + i

In [4]:
print(s)

NameError: name 's' is not defined

In [1]:
for in range (1,11):
    print(i)

SyntaxError: invalid syntax (173346576.py, line 1)

In [6]:
sum_of_number = 0
for num in range(1,11):
    sum_of_number = sum_of_number + num

In [7]:
print(sum_of_number)

55


In [8]:
input int "cost price"
input int "selling price" 


SyntaxError: invalid syntax (134116160.py, line 1)

In [12]:
a = int (input("enter the cost price"))
b = int (input("enter the profit price"))
print(a+b)

enter the cost price100
enter the profit price25
125


# print hello world uptil when c<5

In [14]:
c = 0
while c <5:
    print("hello world")
    c = c+3

hello world
hello world


In [2]:
fruits = ["apple","banana","orange","mango","kiwi"]

for f in fruits:
    if f == "apple":
        continue
        print(f)

In [13]:
a = [1,2,3,"shivam",true,false,2.5]
print(a)

NameError: name 'true' is not defined

In [ ]:
even_number = []
for i in list2:
    if i%2==0:
        even_number.append(i)

In [15]:
even_number

[]

In [ ]:
mixed_list = [1,2,3,] ["hello", "world",]


In [16]:
list = list(range(10))
list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
even_nums =[n for n in e if n%2==0]
even_nums

NameError: name 'e' is not defined

In [22]:
original_list = [1, 2, 3, 4, 5]
reversed_list = original_list[::-1]
print(reversed_list)



[5, 4, 3, 2, 1]


In [23]:
original_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
sublist = original_list[2:7]  
print(sublist)



[3, 4, 5, 6, 7]


In [24]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_numbers = [x for x in numbers if x % 2 == 0]
print(even_numbers)



[2, 4, 6, 8, 10]


In [25]:
squared_numbers = [x**2 for x in range(10)]
print(squared_numbers)



[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [1]:
fruit = ['apple','banana','orange','mango',"kiwi"]
for f in fruits:
    if f == "apple":
        continue
    print(f) 

NameError: name 'fruits' is not defined

In [2]:
for i in range(5):
    if i == 2:
        pass
    else:
        print(i)

0
1
3
4


In [3]:
s1 - x**2
s2 - add 3 to it
s3 - cube the resultant and give the answer
(2**2 + 3)**3 

SyntaxError: invalid syntax (462109658.py, line 2)

In [ ]:
def my func(x):
    r1 = x**2
    r2 = r1 + 3
    r3 = r2**3
    return r3

In [6]:
my_func(2)

NameError: name 'my_func' is not defined

In [7]:
d1 = {"name":"areeb",
     "age":20,
     "cource":"DS"
     "phone number":991}
d1 keys()

SyntaxError: invalid syntax (703523955.py, line 4)

In [8]:
if = "age is above 18"
"enter to party"
Else = dont come hear
print(if+else)

SyntaxError: invalid syntax (1821383472.py, line 1)

In [9]:
numbers = list(range(11))
numbers

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [18]:
if age <=18:
    print("sorry you are not allowed in the club")
elif age>18 and age<=55:
    print("welcome to the party")
else:
    print("oops, you are too old to be here")

NameError: name 'age' is not defined

In [16]:
my_dict = {"name":"rahul","age":25,"gender":"m","cource":"ds",
          "natinallty":"indian"}

In [17]:
print = (my_dict)

In [10]:
my_dict2 = {"name":["rahul","rohit"],
            "age": [26],
            "cource": ["data science"],
            "nationallty":["indian"] }


In [13]:
print(my_dict2)

{'name': ['rahul', 'rohit'], 'age': [26], 'cource': ['data science'], 'nationallty': ['indian']}


In [14]:
a = 2

In [15]:
print(a)

2


In [3]:
my_dict = {"name":"rahul",
"age":25,
"gender":"male",
"cource":"ds",
"natonality": "indian",
"status":"married"}

In [4]:
print(my_dict)

{'name': 'rahul', 'age': 25, 'gender': 'male', 'cource': 'ds', 'natonality': 'indian', 'status': 'married'}


In [5]:
my_dict.pop("gender")

'male'

In [6]:
places = {"india":["up","mp","cp"]}

In [9]:
print(places)

{'india': ['up', 'mp', 'cp']}


In [11]:
keys = ["name","age","gender","color favotite"]
values = ["john",40,"female","black"]

for i in range(len(keys)):
    print(keys[i], values[i])

name john
age 40
gender female
color favotite black


In [13]:
set1= {1,2,3,}
set2 = {3,4,5}



In [17]:
df1 = pd.dataframe(np.random.randn(5,4),["A","B","C","D","E"],'w x y z'.
                   split()df1)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3847134515.py, line 1)

In [3]:
if = <18 
print ("not enter"):
    else = 50>
print ("welcome")

SyntaxError: invalid syntax (1462012518.py, line 1)

In [4]:
name = shivam
age = 24
city = Delhi 

NameError: name 'shivam' is not defined

In [9]:
name = "shivam"
age = 24
city = "delhi" 

In [10]:
print("name","age","city")

name age city


In [9]:
tuple1 = [1,2,3,"shivam","city",2.5]
a=2

In [17]:
print(tuple1)

[1, 2, 3, 'shivam', 'city', 2.5]


In [11]:
A = "hello world"

In [13]:
type(A)

str

In [18]:
print(tuple1)

[1, 2, 3, 'shivam', 'city', 2.5]


In [19]:
tuple1

[1, 2, 3, 'shivam', 'city', 2.5]

In [20]:
set(tuple1)

{1, 2, 2.5, 3, 'city', 'shivam'}

In [21]:
t1 = tuple(list1)
print(t1)

(1, 2, 3, 'shivam', 'city', 2.5)


In [25]:
list1 = list(range(10))
list1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [34]:
for i in list1:
    if i%2==0
    even_number.append(i)

SyntaxError: expected ':' (1729076609.py, line 2)

In [36]:
even_number

NameError: name 'even_number' is not defined

In [40]:
mixed_list = [1,2,3,["hello","world"["shivam Jha"]]]
print (mixed_list)

<>:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
<>:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
C:\Users\shiva\AppData\Local\Temp\ipykernel_15268\324782886.py:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
  mixed_list = [1,2,3,["hello","world"["shivam Jha"]]]
C:\Users\shiva\AppData\Local\Temp\ipykernel_15268\324782886.py:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
  mixed_list = [1,2,3,["hello","world"["shivam Jha"]]]
C:\Users\shiva\AppData\Local\Temp\ipykernel_15268\324782886.py:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
  mixed_list = [1,2,3,["hello","world"["shivam Jha"]]]
C:\Users\shiva\AppData\Local\Temp\ipykernel_15268\324782886.py:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
  mixed

TypeError: string indices must be integers, not 'str'

In [48]:
list1 = [1,2,3,]
list1

[1, 2, 3]

In [51]:
list1.append(4)

In [52]:
list1

[1, 2, 3, 4, 4, 4]

In [57]:
my_list = [1,2,3,4,5,6]
my_list.remove(2)


In [58]:
my_list

[1, 3, 4, 5, 6]

In [69]:
my_list = [1,2,3]
list

list

In [70]:
my_list

[1, 2, 3]

In [79]:
A = [3,5,4,8]
A[3] = "shivam"
print(A)

[3, 5, 4, 'shivam']


In [80]:
print(A)

[3, 5, 4, 'shivam']


In [2]:
list = [10,20,30]
list*2

[10, 20, 30, 10, 20, 30]

In [1]:
shivam = {1,2,3,4,"Jha","shivam"}

In [2]:
type(shivam)

set

In [17]:
shivam = {"name":"shivam","age":5,"gender":"male"}

In [18]:
type(shivam)

dict

In [20]:
import numpy as np


In [21]:
print(np.random.randn(52,48))

[[-1.91339688  0.02203689  0.12446218 ... -1.02904921 -0.44532939
   0.00398858]
 [ 0.02729942  0.90363785 -1.80591064 ... -0.51849737  0.24383959
   0.32548117]
 [-1.17588262 -0.16410987  1.88845039 ... -1.19171456  1.23471382
   1.97469373]
 ...
 [ 0.97872185 -1.10655348 -0.80082811 ...  0.98318178  0.06708609
  -1.87303856]
 [ 0.41916224 -0.66048314 -0.38637914 ...  0.64148487 -0.7538032
   0.53203631]
 [-0.18719176  0.05953108 -0.32652806 ... -1.29147892 -0.45267645
   0.73936428]]


In [22]:
a1 = np.random.randint(1,100,10)
print(a1)

[54 41 85 93 52 97 99 34 63 84]


In [40]:
def greet(shivam):
    print("Greet")


In [6]:
list(rsnge(1,13))

NameError: name 'rsnge' is not defined

In [9]:
list(range(1,13))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [10]:
import numpy as np

In [35]:
array_3x3 = np.zeros((1, 12))

In [16]:
print(array_3x3)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
import numpy as np

In [18]:
array_3x3 = np.arange(1, 10+1).reshape(3, 3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [23]:
print(array_4*4)

NameError: name 'array_4' is not defined

In [20]:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


SyntaxError: invalid syntax. Perhaps you forgot a comma? (507395092.py, line 1)

2.0

In [25]:
arr1+arr2

NameError: name 'arr1' is not defined

In [26]:
arr1 = np.array([1,2,3,])
arr2 = np.array([1,2,3,])

In [27]:
arr1+arr2

array([2, 4, 6])

In [28]:
arr1-arr2

array([0, 0, 0])

In [29]:
arr1*arr2

array([1, 4, 9])

In [30]:
arr1/arr2

array([1., 1., 1.])

In [31]:
print(array_3x3)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [37]:
array = np.one(10)
print(array)

AttributeError: module 'numpy' has no attribute 'one'

In [38]:
import numpy as np

In [40]:
array = np.ones(10)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [41]:
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },


SyntaxError: incomplete input (973733576.py, line 9)